on:
  issue_comment:
    types: [created]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: blacksmith-4vcpu-windows-2025
    steps:
      - uses: actions/checkout@main
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
