on:
  pull_request_target:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: blacksmith-4vcpu-windows-2025
    steps:
      - uses: actions/checkout@main
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
